--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MulqiGaming64/EconomyEnchant
build-by-default: true
branches:
- main
projects:
  EconomyEnchant:
    path: ""
    icon: "icon.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: LatamPMDevs/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
      - src: LatamPMDevs/ConfigUpdater/ConfigUpdater
        version: ^2.0.1
      - src: muqsit/InvMenu/InvMenu
        branch: "pm5"
        version: ^4.6.2
    lint: false
...
