---
name: EconomyEnchant
version: 1.0.1
main: MulqiGaming64\EconomyEnchant\EconomyEnchant
api: 4.0.0
author: MulqiGaming64
description: a EconomyEnchant Shop in UI
softdepend:
 - EconomyAPI
 - BedrockEconomy
 - Capital
 - PiggyCustomEnchants
 - VanillaEC

permissions:
 economyenchant.cmd:
  default: true
  description: EconomyEnchant Commands
...
